import Profile from './profile.models';

export const profile: Profile = {
  experiences: [
    {
      company: {
        location: 'New York - Remote',
        name: 'KnockIQ',
        link: 'https://knockiq.ai',
        image: 'resources/experience/knockiq.png',
        imageStyle: 'width: 40% !important; padding: 1rem;',
        description: `KnockIQ is a pioneering technology company revolutionizing B2B lead generation through advanced artificial intelligence. By leveraging AI-driven insights and real-time engagement tools. KnockIQ empowers businesses to identify and connect with qualified leads.`,
        showName: false,
      },
      title: 'Software Developer',
      startDate: new Date('2025-03-28'),
      coreFunctionalities: ['Backend Development'],
      technologiesAndLanguages: [
        'Ubuntu',
        'Linux',
        'Git',
        'JWT',
        'Express',
        'PostgreSQL',
        'Node',
        'TypeScript',
        'Mailgun',
        'Jira',
        'Confluence',
        'ESLint',
        'Automation Tests',
      ],
    },
    {
      company: {
        location: 'Dubai - Remote',
        name: 'Socienta',
        link: 'https://socienta.com',
        image: 'resources/experience/socienta.png',
        imageStyle: 'width: 40% !important; padding: 1rem;',
        description:
          'Socienta empowers community management companies of all sizes in cutting through complexities of real-estate with a solution to serve landlords & tenants within their communities with the utmost satisfaction.',
        showName: false,
      },
      title: 'Software Development Team Lead',
      startDate: new Date('2022-11-15'),
      coreFunctionalities: ['Software Development', 'Management'],
      technologiesAndLanguages: [
        'Agile',
        'Kubernetes',
        'Linux',
        'Git',
        'JWT',
        'Angular',
        'Express',
        'PostgreSQL',
        'Node',
        'TypeScript',
        'Flutter',
        'Mailgun',
        'SMTP',
        'Jira',
        'Confluence',
        'ESLint',
        'Automation Tests',
      ],
    },
    {
      company: {
        location: 'Dubai - Remote',
        name: 'Socienta',
        link: 'https://socienta.com',
        image: 'resources/experience/socienta.png',
        imageStyle: 'width: 40% !important;padding: 1rem; ',
        description:
          'Socienta empowers community management companies of all sizes in cutting through complexities of real-estate with a solution to serve landlords & tenants within their communities with the utmost satisfaction.',
        showName: false,
      },
      title: 'Software Developer',
      startDate: new Date('2021-08-25'),
      endDate: new Date('2022-11-15'),
      coreFunctionalities: ['Software Development'],
      technologiesAndLanguages: [
        'Agile',
        'Kubernetes',
        'Linux',
        'Git',
        'JWT',
        'Angular',
        'Express',
        'PostgreSQL',
        'Node',
        'TypeScript',
        'Flutter',
      ],
    },
    {
      company: {
        location: 'Latakia - On-site',
        name: 'Code',
        link: '',
        image: 'resources/experience/codeLib.png',
        imageStyle:
          'width: unset !important; height: 12rem !important; filter:invert(1);',
        description:
          'Code Library is focused on preparing high quality and precise lectures for the Faculty of Informatics Engineering at Tishreen University.',
        showName: false,
      },
      title: 'Programming Languages Lectures Writer & Projects Programmer',
      startDate: new Date('2020-03-25'),
      endDate: new Date('2021-08-26'),
      coreFunctionalities: ['Lectures Writing', 'Web Apps Programmer'],
      technologiesAndLanguages: [
        'React',
        'Python',
        'C++',
        'Java',
        'OOP',
        'Microsoft Word',
      ],
    },
    {
      company: {
        location: 'Latakia - On-site',
        name: 'Programming Languages Tutor',
        link: '',
        image: 'resources/experience/teacher.png',
        imageStyle:
          'width: unset !important; height: 12rem !important; filter:invert(1);',
        description: `I've worked as a private teacher for programming languages, following the curricula of Latakia University.`,
        showName: true,
      },
      title: 'Programming Languages Tutor',
      startDate: new Date('2020-03-24'),
      endDate: new Date('2021-08-24'),
      coreFunctionalities: ['Programming Languages Teaching'],
      technologiesAndLanguages: ['Python', 'C++', 'OOP', 'JAVA'],
    },
  ],
  skills: [
    'Angular',
    'Bash',
    'Express',
    'PostgreSQL',
    'MySQL',
    'HTML',
    'CSS',
    'Python',
    'OOP',
    'GIT',
    'NODE',
    'NPM',
    'C++',
    'Java',
    'Typescript',
    'PHP',
    'React',
    'Laravel',
    'Linux',
    'Wordpress',
    'MS Office',
    'RxJS',
  ],
  educations: [
    {
      college: 'Latakia University',
      icon: 'university',
      startDate: new Date('2019-09-20'),
      title: 'College',
      description: 'Bachelor of Technology - BTech, Information Engineering',
      achievements: [
        'Achieved 100% In All Programming Classes (Python, C++, OOP, JAVA)',
      ],
    },
    {
      college: 'Local Secondary School',
      icon: 'school',
      startDate: new Date('2016-09-01'),
      endDate: new Date('2019-09-02'),
      title: 'Secondary School',
      description: 'Bachelor of Science - BS, Scientific',
      achievements: ['Grade: 90%'],
    },
  ],
  about: {
    profileImage: 'resources/profile.webp',
    name: 'Raouf Zeid Albeni',
    job: 'Software Developer',
    birthDate: new Date('2001-11-25'),
    address: 'As Suwayda, Syria',
    addressOnMap: 'https://maps.app.goo.gl/XULPUYCtjJMK2Wau6',
    languages: ['Arabic (Native Language)', 'English (Intermidate)'],
    accounts: [
      {
        url: 'https://www.linkedin.com/in/albeniraouf',
        website: 'LinkedIn',
        icon: 'linkedin',
      },
      {
        url: 'https://github.com/albeniraouf',
        website: 'Github',
        icon: 'github',
      },
      {
        url: 'https://www.facebook.com/albeniraouf',
        website: 'Facebook',
        icon: 'facebook',
      },
      {
        url: 'https://www.instagram.com/albeniraouf',
        website: 'Instagram',
        icon: 'instagram',
      },
    ],
    // whoAmI: `
    // <p align="left">
    //   I'm currently pursuing a degree in Information Engineering and working as a Full-Stack Software Developer and Team Leader, with a strong focus on web development.<br/>
    //   I'm highly passionate about technology, a fast learner, capable of multitasking effectively, and committed to delivering high-quality work. My career began during my studies, teaching programming language courses and writing programming lectures.<br/>
    //   I later joined <b>Socienta</b> as a Software Developer, working primarily with Angular, Express, and PostgreSQL. Over time, I took on more responsibilities and eventually stepped into a Team Leader role.<br/>
    //   In parallel, I also started working with <b>KnockIQ</b> as a Backend Developer, where I focus on building scalable backend systems using Express, Prisma, and PostgreSQL.<br/>
    // </p>`,
    whoAmI: [`I'm currently pursuing a degree in Information Engineering and working as a Full-Stack Software Developer and Team Leader, with a strong focus on web development.<br>...`,
      `I'm currently pursuing a degree in Information Engineering and working as a Full-Stack Software Developer and Team Leader, with a strong focus on web development.<br>I'm highly passionate about technology, a fast learner, capable of multitasking effectively, and committed to delivering high-quality work. My career began during my studies, teaching programming language courses and writing programming lectures.<br>...`,
      `I'm currently pursuing a degree in Information Engineering and working as a Full-Stack Software Developer and Team Leader, with a strong focus on web development.<br>I'm highly passionate about technology, a fast learner, capable of multitasking effectively, and committed to delivering high-quality work. My career began during my studies, teaching programming language courses and writing programming lectures.<br>I later joined <b>Socienta</b> as a Software Developer, working primarily with Angular, Express, and PostgreSQL. Over time, I took on more responsibilities and eventually stepped into a Team Leader role.<br>...`,
      `I'm currently pursuing a degree in Information Engineering and working as a Full-Stack Software Developer and Team Leader, with a strong focus on web development.<br>I'm highly passionate about technology, a fast learner, capable of multitasking effectively, and committed to delivering high-quality work. My career began during my studies, teaching programming language courses and writing programming lectures.<br>I later joined <b>Socienta</b> as a Software Developer, working primarily with Angular, Express, and PostgreSQL. Over time, I took on more responsibilities and eventually stepped into a Team Leader role.<br>In parallel, I also started working with <b>KnockIQ</b> as a Backend Developer, where I focus on building scalable backend systems using Express, Prisma, and PostgreSQL.`
    ],
    emails: ['raouf.albeni@gmail.com', 'raouf.albeni@yahoo.com'],
    phones: ['+963 949 294 811', '+963 981 241 453'],
  },
  certifications: [
    {
      date: new Date('2025-04-01'),
      title: 'Spotlight of the Quarter - Q1 2025',
      description: 'Awarded to be the Spotlight of the Quarter One of 2025',
      origin: 'Socienta',
      img: 'resources/certificates/socientaQ1Spotlight.png',
    },
  ],
};
